### PR TITLE
Set the env variable MOZCONFIG in launchd too

### PR DESCRIPTION
**Pull request by eoger**
I couldn't build Fennec using Android Studio without setting the environment variable in launchd.

### CODE REVIEW

**Comment by ahal** [comment]
Thanks for the patch, though I can't accept this because it assumes `launchctl` exists on the user's system. Maybe instead of calling launchctl directly here, we could create a new `MOZCONFIG_EXPORT_COMMAND` environment variable that defaults to `export MOZCONFIG=`. Then you could set that variable to `launchctl setenv` in your shell.

**Comment by eoger** [comment]
Thank you, it was a pretty bad idea indeed, I amended my patch (which allows to run multiple commands, since we do string substitution).

**Comment by eoger** [comment]
Polite bump

**Comment by whimboo** [comment]
@ahal maybe you missed the update?

**Comment by ahal** [comment]
Yes, my apologies. Just tested and this looks good, thanks! I'll merge now.

p.s I know I suggested ``MOZCONFIG_EXPORT_COMMAND`` but I'm going to change the name to ``BUILDWITH_COMMAND`` for consistency with the existing ``BUILDWITH_HOME`` variable.

**Pull request merged**
